### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by jspaulsen** [slank/awsgi#51]
Getting the following error with 0.2.6

```
[ERROR] TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/var/task/app/app.py", line 21, in entrypoint
    return awsgi.response(api, event, context)
  File "/var/task/awsgi/__init__.py", line 172, in response
    return sr.response(output)
  File "/var/task/awsgi/__init__.py", line 94, in response
    rv = super(StartResponse_GW, self).response(output)
  File "/var/task/awsgi/__init__.py", line 88, in response
    rv.update(self.build_body(headers, output))
  File "/var/task/awsgi/__init__.py", line 69, in build_body
    is_b64 = self.use_binary_response(headers, totalbody)
  File "/var/task/awsgi/__init__.py", line 60, in use_binary_response
    if ';' in content_type:
```

Appears directly related to #50

**Comment by slank** [comment]
Thanks @jspaulsen!
