### ISSUE TITLE
Crash after upgrade to 0.2.6 when no Content-Type header is set in response

### ISSUE THREAD

**Issue by uscheller** [slank/awsgi#54]
After upgrading to version 0.2.6, I have the following issue on responses without a "Content-Type" header set:

`[ERROR] TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/var/task/src/main/handler.py", line 262, in flask_handler
    return awsgi.response(app, event, context)
  File "dependencies/awsgi/__init__.py", line 172, in response
    return sr.response(output)
  File "dependencies/awsgi/__init__.py", line 94, in response
    rv = super(StartResponse_GW, self).response(output)
  File "dependencies/awsgi/__init__.py", line 88, in response
    rv.update(self.build_body(headers, output))
  File "dependencies/awsgi/__init__.py", line 69, in build_body
    is_b64 = self.use_binary_response(headers, totalbody)
  File "dependencies/awsgi/__init__.py", line 60, in use_binary_response
    if ';' in content_type:`

My case is an empty response with a 304 status code, so there is no content. The culprit seems to be this commit:

https://github.com/slank/awsgi/commit/00c375c4e87a61d336ac44870dbcc8e16234cf37

`>>> ';' in None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument of type 'NoneType' is not iterable`

A fix would be to check for None

**Comment by jspaulsen** [comment]
This was addressed in https://github.com/slank/awsgi/issues/51 though it appears the minor version wasn't bumped :thinking:

**Comment by uscheller** [comment]
Thank you. I didn't check the closed issues.

**Comment by slank** [comment]
Sorry about that. I have bumped the version.
